INSERT INTO questions (id, question, answer) VALUES
(1, 'One of the following is a danger sign of oral contraceptive pills', 'C. Deep vein thrombosis'),
(2, 'Which of the listed drugs is a major anti-convulsant used under the PAC level essential drug list', 'C. Injection paraldehyde'),
(3, 'One of the following is not among the role of CHO in mental health Care', 'C. Therapeutic'),
(4, 'The thyroid gland is the largest endocrine gland situated in', 'C. Anterior aspect of the neck'),
(5, 'The primary cause of sickle cell disease is', 'A. Genetic'),
(6, 'One of the following is a cause for changes in respiratory system', 'C. cancer'),
(7, 'Identification of handicap and disability will be best carried out during all except one', 'D. Integrated PHC services'),
(8, 'Poisoning can result from all the following except:', 'B. Heat radiation'),
(9, 'Components of focus antenatal care does not include one of this', 'D. Inoculation of sulphadoxine pyrimethamine injection'),
(10, 'One of these is not a component of standing orders', 'C. Abstract'),
(11, 'A sudden onset of symptoms or illness that typically has a short duration and often severe is called', 'C. Acute condition'),
(12, 'Which of the following best defines first Aider does not', 'D. One who is sick'),
(13, 'Statistics in the contemporary health system is best described as', 'B. A branch of applied mathematics that involves the collection, description, analysis and inference on conclusion from quantitative data for decision making'),
(14, 'Emergency preferred pathway means', 'C. You can skip normal pathway to seek for appropriate care'),
(15, 'Decalcification of a tooth means', 'D. Removal of calcium salts from the bone of the tooth'),
(16, 'The small baby encounters all except one of these possible complications except', 'C. Placental problem'),
(17, 'The pulse is:', 'D. Physical expansion of artery indicating heart beats'),
(18, 'Which of the following is not a component of HMIS', 'B. Data encryption'),
(19, 'The measure of incidence of death within a population is________________________.', 'D. Mortality rate'),
(20, 'One of this is not included in the principles of management', 'B. Dedication'),
(21, 'A type of probability sampling method where each member of the population has an equal chance of being selected as part of the sample is called', 'D. Simple random sampling'),
(22, 'The measure used to compare one variable and the other is:', 'B. Ratio'),
(23, 'One of the following is not a function of blood:', 'B. Photo regulation'),
(24, 'Abnormal breath sounds exclude:', 'D. Murmur'),
(25, 'The scientific method of finding out by investigation and analysis the cause of disease and how to manage it appropriately is:', 'D. Epidemiological skill'),
(26, 'The disease to be reported to disease notification officer (DSNO) at the LGA level as soon a diagnosed at the health facility does not includes', 'D. Malaria fever'),
(27, 'Post medical history is necessary to gather information about the patients’ _________ and ___________', 'C. Previous illness and treatment'),
(28, 'All except one is instruments used during outreach services', 'D. Clinic master card'),
(29, 'The characteristics of a mentally retarded person does not include', 'C. Frequent intake of alcohol'),
(30, 'One of these is not true about communicable diseases:', 'A. They have risk factors instead of causative agent'),
(31, 'These are all types of STIs except', 'C. Liver cirrhosis'),
(32, 'The commonest virus linked to the development of cervical cancer is:', 'B. Human papilloma virus'),
(33, 'Factors affecting the utilization of family planning services are ---------------', 'D. Well trained and motivated health worker'),
(34, '---------------------- is a non-inflammatory determination of articular cartilages', 'A. Osteoarthritis'),
(35, 'The type of obsessive-compulsive disorder excludes', 'B. Obsessive reputation'),
(36, 'One of the following is not among the phases of community needs assessment', 'A. Post assessment'),
(37, 'Risk factors associated with cardiac disease among the elderly is', 'D. Regular intake of alcohol'),
(38, 'One of the following is not a viral disease', 'A. Balantidiasis'),
(39, 'In community based newborn care, home visit for birth preparedness is seen as;', 'B. Beneficial intervention'),
(40, 'Manifestation of anaemia does not include one of the following:', 'D. Hunger'),
(41, 'Which of the following disease is not a common cause of blindness among the elderly', 'A. Conjunctivitis'),
(42, 'Psychotic disorder exclude:', 'D. Schizophrenia'),
(43, 'The purpose of supervision in Primary Health Care includes', 'A. To detect lapses and offer technical corrections where necessary'),
(44, 'The anatomical and functional unit of the kidney is called', 'C. Nephron'),
(45, 'The classification of leucocytes that are capable of engulfing and destructing of foreign bodies are the', 'B. Macrophages and neutrophils'),
(46, 'The two major rehabilitation services in primary health care are?', 'C. Basic rehabilitation and vocational rehabilitation'),
(47, 'Condition not covered by the Standing Orders should be:', 'D. Referred to higher level of care'),
(48, 'One of the causes of acute renal failure in obstetrics is:', 'C. Excessive loss of fluid and electrolytes as in hyperemesis gravidarum'),
(49, 'In selection of essential drugs for PHC, all are correct except one', 'B. Certification'),
(50, 'The first line of drug for the treatment of hypertension is________________________..', 'B. Antihypertensive drugs');


INSERT INTO questions (id, question, answer) VALUES
(51, 'Information system used for accessing, monitoring, organizing and visualizing reports of disease outbreaks according to geography, time and infectious disease agent, is best described as ---------------', 'C. Health map'),
(52, 'One of the following is not a sign of gangrene', 'D. Absence of pain at the affected area'),
(53, 'Which of these is not among the job factors affecting choice of style of supervision', 'B. Need for ‘find fault’'),
(54, 'Methods used in community diagnosis includes;', 'D. Observation, questionnaire, interview, group discussion, review of existing records'),
(55, 'Urinary bladder and sigmoid colon are located at which region of the abdomen', 'D. Hypogastric region'),
(56, 'A condition characterized by excessive bleeding during menstruation is medically referred to as', 'B. Menorrhagia'),
(57, 'One of the following options is not a remedy for the aged muscular skeletal problem', 'D. Adequate nutrition'),
(58, 'The following complication can occur as a result of severe Anaemia', 'C. Heart attack'),
(59, 'One of the following is not a measure of central tendency', 'B. Media'),
(60, 'In the procedure for tepid sponging, a child should be', 'A. Undressed'),
(61, 'The only solid part of the eye is --------------------------', 'C. The cornea'),
(62, 'Which of the following do the time, place and person characteristics of disease in epidemiology refer to?', 'A. Distribution'),
(63, 'Two types of cell division are_________ and ___________', 'A. Mitosis and meiosis'),
(64, 'Preterm babies born before ---------------- weeks of gestation', 'A. 36'),
(65, 'In history taking, one of the following areas can be ignored', 'C. History of conflict in the community'),
(66, 'One of the following is not a benefit of oral contraception:', 'D. Increased breast tenderness'),
(67, 'The nerve that connects the eye to the brain is --------------------', 'B. Optic nerve'),
(68, 'A depression of the anterior fontanelle of newborn is commonly as a result of', 'C. Dehydration'),
(69, 'Purpose of motivation in Primary Health Care does not include', 'A. It facilitates un-realization of set objectives'),
(70, 'One of the following test strips is not commonly used in ANC clinic', 'C. Lipolysis strip'),
(71, 'The largest part of the brain is known as', 'B. Cerebrum'),
(72, 'HIV is a transmissible ---------------- that affects or weakens the immune system', 'B. Viral infection'),
(73, 'The type of diarrhea commonly associated with HIV infection and is characterized by persistent watery diarrhea', 'A. Chronic diarrhea'),
(74, 'The process of packaging drugs in dispensing materials prior to the outpatient session is referred to as', 'A. Drug pre-packaging'),
(75, 'Causes of domestic accident does not include one of the following:', 'C. Provision of protective rails'),
(76, 'A disease that cannot be transferred from one person to another is ----------------', 'B. Non communicable diseases'),
(77, 'Intervention packages in community based newborn care, does not include;', 'B. Birth spacing at the age of 13'),
(78, 'The joining of mid-point of a histogram result to:', 'C. Frequency polygon'),
(79, 'The black part of the eye is best described as --------------------', 'C. Pupil'),
(80, 'The causes of population growth includes', 'C. Poverty, child labour, fertility treatment, immigration'),
(81, 'The principle of management which states that responsibility, authority and accountability should be shared with subordinates, while the manager still maintains control is called', 'C. Delegation'),
(82, 'The best immediate treatment for a chemical splash to the eye is', 'A. Copious irrigation with water'),
(83, 'One of the following is not among the Universal Precautions for Laboratory safety:', 'C. Blood culture and sensitivity'),
(84, 'One of the following is not a type of muscle tissue', 'B. Ciliated muscles'),
(85, 'Factors that cannot influence the spread of HIV/AIDs ---------------', 'D. Political factors'),
(86, 'Inferential statistics excludes:', 'B. Variance'),
(87, 'The number of people who live in a specified geographical area during a defined time e.g. state, country and town is', 'B. Population size'),
(88, 'Which of the following is not an importance of financial reporting', 'A. Performance of the organization and its management not analysed'),
(89, 'The formula for calculating Maternal Mortality Rate (MMR) is:', 'C. MMR = Number of maternal deaths * 100,000 / Number of live births'),
(90, 'The AYFHS, as an acronym in adolescence means', 'A. Adolescent and youth friendly health services'),
(91, 'One of the following should not be considered when communicating with a sensorineural hearing loss person', 'C. Shout as loudly as possible next to their ear'),
(92, '---------------- and ------------- are permanent methods of family planning', 'B. Vasectomy and Tubal ligation'),
(93, 'A disease where the signs and symptoms occur suddenly and last for a relative short period is termed:', 'A. Acute'),
(94, '--------------- can be defined as a decrease in the haemoglobin level of an individual', 'C. Anaemia'),
(95, 'One of the following is a characteristic symptom of anemia', 'A. Fatigue and weakness'),
(96, 'Measures of morbidity does not include:', 'D. Parity rate'),
(97, 'In PHC system, data collection management scales of management used all except one', 'B. Rational scale'),
(98, 'All the following are challenges of immunization coverage except one', 'D. Health workers/patients’ relationship'),
(99, 'One of the following is not a concept used in anatomy and physiology', 'A. Diastema'),
(100, 'One of the following is not among the component of maintaining the efficacy of vaccines', 'A. Human resources');

